# Generated by Django 5.2.1 on 2026-04-20 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_galleryitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryitem',
            options={'ordering': ['-created_at']},
        ),
    ]
