# Generated by Django 5.2.1 on 2026-04-20 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_galleryitem_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GalleryItem',
            new_name='Gallery',
        ),
    ]
